- name: Use S3cmd
    uses: s3-actions/s3cmd@v1.2.0
    with:
    provider: aws
    region: 'eu-central-1'
    access_key: ${{ secrets.S3_ACCESS_KEY }}
    secret_key: ${{ secrets.S3_SECRET_KEY }}

- name: Interact with object storage
  run: |
          s3cmd pull s3://genome-idx/kraken/k2_pluspf_8gb_20220607.tar.gz
          tar -xvf k2_pluspf_8gb_20220607.tar.gz
