# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: download kraken
      run: |
          wget https://genome-idx.s3.amazonaws.com/kraken/k2_pluspf_16gb_20220908.tar.gz
          tar -xvf k2_pluspf_8gb_20220607.tar.gz -C k2_pluspf_16gb/
    - name: download bowtie
      run: |
          wget ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19_1kgmaj_bt2.zip
          unzip hg19_1kgmaj_bt2.zip -d hg19_1kgmaj